spring:
  cloud:
    config:
      label: main
      server:
        git:
          uri: https://github.com/NeverL1/center-config
          username: 1724906127@qq.com
          password: wsljchaha1
  application:
      name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  #自己不注册
  client:
    register-with-eureka: false
  #表示是否从Eureka Server获取注册的服务信息
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

opentracing:
  jaeger:
    enabled: true
    log-spans: true
    const-sampler:
      decision: true
    #将日志发送到agent
    udp-sender:
      host: localhost
      port: 6831

ribbon:
  eureka:
    enabled: true